name: odc_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  iconsax: 
  lottie: 
  shimmer: 
  intl: ^0.20.2
  connectivity_plus: ^6.1.3
  shared_preferences: ^2.5.2
  sqflite: ^2.4.2
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  another_flutter_splash_screen: ^1.2.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  flutter_bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true


  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/svgs/